# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0d613a8184058e40f2808e7c6991bffa5530d065690515776fae53ca02cf33f3cafa4c2bc99c5e70b104abb95b931a67ee770a572bdcf1de8c6b67193bedf78

test:
  secret_key_base: 468d5a9cb604e5fc0599c6d35b0efb6499132cb88221d34c0820601e84dc85b45ba81706a5022554a06ad96eccdc87bbdfe08fd43a6b4706c7d040945a65296e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
